# coding: utf-8

# flake8: noqa

"""
    Weather API

    # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY    # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys

# import all weatherapi subpackages into swagger_client namespace
import weatherapi
from weatherapi import *

# import apis into sdk package
from weatherapi.api.apis_api import APIsApi

# import ApiClient
from weatherapi.api_client import ApiClient
from weatherapi.configuration import Configuration
# import models into sdk package
from weatherapi.models.alerts import Alerts
from weatherapi.models.alerts_alert import AlertsAlert
from weatherapi.models.array_of_search import ArrayOfSearch
from weatherapi.models.astronomy import Astronomy
from weatherapi.models.astronomy_astro import AstronomyAstro
from weatherapi.models.current import Current
from weatherapi.models.current_air_quality import CurrentAirQuality
from weatherapi.models.current_condition import CurrentCondition
from weatherapi.models.error400 import Error400
from weatherapi.models.error401 import Error401
from weatherapi.models.error403 import Error403
from weatherapi.models.forecast import Forecast
from weatherapi.models.forecast_astro import ForecastAstro
from weatherapi.models.forecast_condition import ForecastCondition
from weatherapi.models.forecast_day import ForecastDay
from weatherapi.models.forecast_day_condition import ForecastDayCondition
from weatherapi.models.forecast_forecastday import ForecastForecastday
from weatherapi.models.forecast_hour import ForecastHour
from weatherapi.models.ip import Ip
from weatherapi.models.location import Location
from weatherapi.models.marine import Marine
from weatherapi.models.marine_forecastday import MarineForecastday
from weatherapi.models.marine_hour import MarineHour
from weatherapi.models.search import Search

# Alias all weatherapi module names to swagger_client names, so that
# imports of swagger_client.foo work.
swagger_packages = {
    k.replace('weatherapi', 'swagger_client'): v
    for k, v in sys.modules.items()
    if k.startswith('weatherapi')
}
sys.modules.update(swagger_packages)
del swagger_packages

